name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa uma vez por dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: DanieleChagasSouza
          output: dist/github-contribution-grid-snake.svg

      - name: Push generated snake.svg to the output branch
        uses: actions/upload-artifact@v2
        with:
          name: snake-graph
          path: dist/github-contribution-grid-snake.svg
